repository:
  name: find-terraform-modules
  description: GitHub Action to find all Terraform module directories in a monorepo
  default_branch: main
  topics: terraform, github-actions
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - test
labels:
  - name: automerge
