name: Find Terraform Modules
description: Finds all Terraform module directories in a monorepo. Results can be passed to matrix jobs or looped in other steps.
author: Ben Drucker <bvdrucker@gmail.com> (https://www.bendrucker.me)
inputs:
  working-directory:
    required: false
    description: 'The working directory where Terraform modules will be matched'
    default: '.'
  follow-symbolic-links:
    required: false
    description: 'Indicates whether to follow symbolic links'
    default: 'true'
runs:
  using: 'node12'
  main: 'dist/index.js'
